### ISSUE TITLE
Add Additional Authenticated Data (AAD) to API

### ISSUE THREAD

**Issue by cygnusv** [nucypher/ferveo#1]
Additional Authenticated Data (AAD) is an arbitrary, non-private bytestring that's included at encryption and decryption time for further validation of ciphertexts. In the context of the Ferveo design, it's also possible to publicly validate a ciphertext, including the AAD in the process. For us, the AAD is the simplest way to attach conditions and other metadata to ciphertexts.

However, for some reason the Ferveo implementation didn't include the AAD as an input to the encryption API (and therefore to the decryption and ciphertext validation APIs); they're just not using it. See https://github.com/nucypher/ferveo/blob/main/tpke/src/ciphertext.rs#L56

We need to add the AAD as an input to the encryption, decryption and ciphertext validation functions, as well as using this AAD when creating the ciphertext authentication tag.

**Comment by cygnusv** [comment]
After further inspection, the `construct_tag_hash` function that creates the authentication tag also differs from the specification in that it's applied on top of the symmetric part of the ciphertext, and not the AAD. We need to fix that as well.

**Comment by theref** [comment]
are we going to be maintaining our own copy of Ferveo rather than contributing to the main repo?

**Comment by cygnusv** [comment]
I've just realized they're using Chacha20 as the cipher algorithm, which is not an AEAD cipher. Ideally, we'd use Chacha20Poly1305. 

> are we going to be maintaining our own copy of Ferveo rather than contributing to the main repo?

We're forking it, and will create PRs in the original repo when possible.
