### ISSUE TITLE
Add header and payload to Ciphertext bindings

### ISSUE THREAD

**Issue by cygnusv** [nucypher/ferveo#154]
To facilitate the creation of TDec Requests after the changes introduced by #149, we need a set of helper functions to facilitate getting the necessary information, i.e., commitment U, authentication tag W and hash of the symmetric ciphertext. Tentatively, let's call this the header, and for the bulk of the symmetric ciphertext, let's call it the payload. This is what just something that we need above the ferveo level, so that's why I'm suggesting doing this in the bindings

**Comment by piotr-roslaniec** [comment]
Just to get on the same page:

```Rust
// No changes
pub struct Ciphertext<E: Pairing> {
    // U
    pub commitment: E::G1Affine,
    // W
    pub auth_tag: E::G2Affine,
    // V
    pub ciphertext: Vec<u8>,
}

impl<E: Pairing> Ciphertext<E> {
	// ...
	pub fn header(&self) -> CiphertextHeader<E> { ... }
	pub fn payload(&self) -> CiphertextPayload
}

pub struct CiphertextHeader<E: Pairing> {
    // U
    pub commitment: E::G1Affine,
    // W
    pub auth_tag: E::G2Affine,
    // sha256(V)
    pub ciphertext_hash: Vec<u8>,
}

pub type CiphertextPayload = Vec<u8>;
```

**Comment by cygnusv** [comment]
Yes, I think that sounds fine, but let's see what @derekpierre thinks, since he asked for this to facilitate the work in the nucypher-core and nucypher layers. The point here is to add this just as a helper function for nucypher-core consumption, without impacting anything else on the Ferveo side.

> IMHO we just need to zero in on the data structures

Can you elaborate on this?

**Comment by piotr-roslaniec** [comment]
> Can you elaborate on this?
I was just trying to say that even thought I'm not familiar with the upstream of this issue, it seems to be like implementing these structures will require a minor refactor, and it should be fairly easy.

**Comment by piotr-roslaniec** [comment]
Drafter updated `Ciphertext` API here: https://github.com/nucypher/ferveo/pull/155

**Comment by piotr-roslaniec** [comment]
`check_ciphertext_validity` method implements one of the verification methods outlined by the original Ferveo implementation. It requires the [availability of the `ciphertext`](https://github.com/nucypher/ferveo/blob/5062f40280ff9bc5dd1ca98d5fcd19d3344ab71f/tpke/src/ciphertext.rs#L113-L113) when creating a decryption share.

Does it make sense to compute the "tag hash" (`hash_g2` in the code example) on the encrypter side and contribute it to `CiphertextHeader`? Does it break the 4.4.2 validity check?

**Comment by cygnusv** [comment]
Closed by https://github.com/nucypher/ferveo/pull/155
