### ISSUE TITLE
Hash function selection for `tpke`

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/ferveo#16]
> We need to be careful with hash function selection, specially if there's stuff that has to be executed later on-chain. Although there's a precompile for the internal function F for Blake2 (https://eips.ethereum.org/EIPS/eip-152), we need to consider it. We don't want to end up with a hash function salad like it happened with our first Umbral implementation, where Blake2b, SHA256 and keccak256 had to coexist. In rust-umbral we switched to SHA256 for everything.
> 
> In any case, this is not a comment for this PR, but an issue to be opened.

_Originally posted by @cygnusv in https://github.com/nucypher/ferveo/pull/8#discussion_r1023919845_

**Comment by piotr-roslaniec** [comment]
If we want to use Ethereum-compatible hashing functions, it seems like the choice is between sha256, sha3fips256 (keccak256), and ripemd160 ([1](https://docs.moonbeam.network/builders/pallets-precompiles/precompiles/eth-mainnet/#hashing-with-sha256))

Is there any reason not use sha256? My understanding of blake2 vs sha256 is that sha256 is a Merkle-Damgård construct and unlike blake2b is not [random oracle indifferentiable](https://blog.cryptographyengineering.com/2012/07/17/indifferentiability/). Is that property a must have? 

We're using blake2b to produce [nonce](https://github.com/nucypher/ferveo/pull/8/files/d9e43a4cebaeb11a3e8c44bbef5933c5f52627ae..5f5b5f35ea6d9460ebfa55e9aeeeb2ef46b76105#diff-77fd8e16ac649ad31c2c194cc79b5f867795266417d190b9d372609b92d7e2b6R144-R145), and to transform the shared secret into an [encryption key](https://github.com/nucypher/ferveo/pull/8/files/d9e43a4cebaeb11a3e8c44bbef5933c5f52627ae..5f5b5f35ea6d9460ebfa55e9aeeeb2ef46b76105#diff-77fd8e16ac649ad31c2c194cc79b5f867795266417d190b9d372609b92d7e2b6R134-R136) for ChaCha20Poly1305. If feel like at least in the case of the former using sha256 is permissible.

**Comment by cygnusv** [comment]
Relevant discussion https://github.com/nucypher/rust-umbral/issues/2

**Comment by piotr-roslaniec** [comment]
It looks like `hash_to_curve` implementation in Ferveo [already uses sha256](https://github.com/nucypher/ferveo/pull/14/files#diff-74519efce5ba104cb3b18a0a4cf7bd2b40a8bf8bd1d8069512ed9690856d6bf7R108-R117). In that case, should we move forward with the transition to sha256?

**Comment by cygnusv** [comment]
Where does Ferveo use Blake2b?

**Comment by piotr-roslaniec** [comment]
Ferveo is using blake2b to transform the shared secret into an [encryption key](https://github.com/nucypher/ferveo/pull/8/files/d9e43a4cebaeb11a3e8c44bbef5933c5f52627ae..5f5b5f35ea6d9460ebfa55e9aeeeb2ef46b76105#diff-77fd8e16ac649ad31c2c194cc79b5f867795266417d190b9d372609b92d7e2b6R134-R136) for ChaCha20Poly1305

We've recently made a change to also use it produce [commitment (previously called nonce)](https://github.com/nucypher/ferveo/pull/8/files/d9e43a4cebaeb11a3e8c44bbef5933c5f52627ae..5f5b5f35ea6d9460ebfa55e9aeeeb2ef46b76105#diff-77fd8e16ac649ad31c2c194cc79b5f867795266417d190b9d372609b92d7e2b6R144-R145), for ciphertext.

**Comment by piotr-roslaniec** [comment]
This is how those changes shape up: https://github.com/nucypher/ferveo/pull/19
