### ISSUE TITLE
Aggregate transcript from a subset of participants

### ISSUE THREAD

**Issue by cygnusv** [nucypher/ferveo#179]
As part of the efforts to add some fault-tolerance to our DKGs ( https://github.com/nucypher/nucypher/issues/3425 ) as well as for Refresh & Recovery, there is the need to produce aggregate transcripts that don't include all participants in transcripts, but only a subset. 

For example, during the proposed fault-tolerant DKG rituals, at the end of phase 1 there may be more than `N` transcripts, each containing `N+B` elements, but the aggregate transcript should only contain `N` elements.

**Comment by piotr-roslaniec** [comment]
Closed by #185
