### ISSUE TITLE
Expand benchmark suite in `tpke` crate

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/ferveo#24]
Currently, we only have benchmarks for the share combination method of the fast threshold decryption variant.

We want to add more benchmarks to the `tpke` crate for the following:

- Fast & simple threshold decryption, #25  
  - [x] Creating a decryption share
  - [x] Preparing share combination 
  - [x] Share combination
-  [x] Encryption & decryption, #25  
- Key share refreshing & recovery (delayed, and to be revised later, #41
  - [x] Computing share updates
  - [x] Refreshing a share 

RFC @cygnusv

**Comment by cygnusv** [comment]
We need benchmarks for the following primitives:
### Group operations
* `mul` for `G1Projective`, `G1Affine`, `G2Projective`, `G2Affine`
* `into_affine` for `G1Projective`, `G2Projective`
* `into_projective` for `G1Affine`, `G2Affine`
* `prepare_g1` for `G1Affine`
* `prepare_g2` for `G2Affine`
* `pow` for `Fqk` elements (i.e., `G_T` elements)

### Pairing operations
* `miller_loop` (for 1, 2, 4, ..., 64 inputs) 
* `final_exponentiation` (for a `miller_loop` result)
* `product_of_pairings` (for 1, 2, 4, ..., 64 inputs) 
* `pairing`

**Comment by theref** [comment]
It would be good to get an idea whether we should be using  https://github.com/arkworks-rs/algebra/tree/master/poly for our polynomials as well

**Comment by cygnusv** [comment]
> Key share refreshing & recovery
> * [ ]  Computing share updates
> * [ ]  Refreshing a share

There are heavily distributed algorithms, don't involve TDec consumers, and are not time-sensitive, so I don't think there's priority to add benchmarks to the above.

**Comment by piotr-roslaniec** [comment]
> We need benchmarks for the following primitives:

Would it be interesting to have this in another repo? I think there is little point in keeping those in our repository (and running them alongside other benchmarks) since it's an external dependency and would only get one once per release essentially.

**Comment by piotr-roslaniec** [comment]
There are some related benchmarks in the [`ferveo` crate](https://github.com/nucypher/ferveo/blob/main/ferveo/benches/benchmarks/pairing.rs), but not exactly what we're looking for.

**Comment by cygnusv** [comment]
> > We need benchmarks for the following primitives:
> 
> Would it be interesting to have this in another repo? I think there is little point in keeping those in our repository (and running them alongside other benchmarks) since it's an external dependency and would only get one once per release essentially.
> 
> We could reuse some [benchmarks and benchmarking utilities ](https://github.com/arkworks-rs/curves/blob/v0.3.0/curve-benches/benches/bls12_381.rs)from Arkworks.

We certainly don't need to run it as part of CI, but we could just have it there as a script to run locally when needed
