### ISSUE TITLE
Ensure presence and correctness of validity checks

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/ferveo#31]
Revise Ferveo's [whitepaper](https://eprint.iacr.org/2022/898.pdf) and [docs](https://nikkolasg.github.io/ferveo/prefix.html). List all validity checks for the protocol. Revise the source code and make sure that those checks are present, correct, and tested. Devise green- and red path scenarios.

List of checks:
- [x] #42
- #44 - moved, postponed
- #45 - moved, postponed

---

- [x] Ciphertext Validity Checking - must be done **before** creating a decryption share
- https://github.com/nucypher/ferveo/pull/38
<img width="830" alt="Screenshot 2023-01-16 at 10 20 03" src="https://user-images.githubusercontent.com/4128101/212642255-311cbb2f-3373-46eb-af48-bfa20e061623.png">

---

- [x] Verifying Decryption Shares - must be done **before** combining decryption shares
	- [x] [`batch_verify_decryption_shares`](https://github.com/piotr-roslaniec/ferveo/blob/main/tpke/src/context.rs#L59-L59)
	  - Used to be called in the original [`tpke` benchmark](https://github.com/anoma/ferveo/blob/8363c33d1cf79f93ce9fa89d4b5fe998a5a78c26/tpke/benches/benchmarks.rs#L99)
	  - Checks that  $e([\sum_j \alpha_{i,j} ] D_i, B_i)$ matches $e(\sum_j [ \sum_i \alpha_{i,j} ] U_j, -H)$ (?)
	  		- $B_i = [b_i] H$, `blinding_key_prepared` 
	- Also described in [docs](https://nikkolasg.github.io/ferveo/tpke-concrete.html#tpkeverifydecryptionsharesek_i--u_j---d_ij----bool)
	  - https://github.com/nucypher/ferveo/pull/38
	  - [x] Existing implementation works for the fast tDec variant
      - [x] Check for simple tDec variant is backlogged #42
<img width="824" alt="Screenshot 2023-01-16 at 10 22 07" src="https://user-images.githubusercontent.com/4128101/212642673-b8d6c331-9409-4775-a696-3ede4c598e2e.png">
<img width="810" alt="Screenshot 2023-01-16 at 11 06 47" src="https://user-images.githubusercontent.com/4128101/212652257-ab5f9ce6-817a-481d-a2aa-9adf5cf71df1.png">

---

`ferveo`:
- [x] [`verify_optimistic`](https://github.com/piotr-roslaniec/ferveo/blob/main/ferveo/src/vss/pvss.rs#L106-L106)
  - [Usage example](https://github.com/piotr-roslaniec/ferveo/blob/benchmarks-pr-compare/ferveo/src/dkg/pv.rs#L163-L163) 
  - [x] Already tested with positive and [negative](https://github.com/nucypher/ferveo/blob/benchmarks-pr-compare/ferveo/src/vss/pvss.rs#L269-L269) examples.
  - This one is effectively done, we just need to make sure we know what it does and whether we are happy with using it

**Comment by theref** [comment]
- [ ] Ciphertext Validity Checking
<img width="830" alt="Screenshot 2023-01-16 at 10 20 03" src="https://user-images.githubusercontent.com/4128101/212642255-311cbb2f-3373-46eb-af48-bfa20e061623.png">
This must be done *before* creating a decryption share

**Comment by theref** [comment]
- [ ] Verifying Decryption Shares - must be done **before** combining decryption shares
<img width="824" alt="Screenshot 2023-01-16 at 10 22 07" src="https://user-images.githubusercontent.com/4128101/212642673-b8d6c331-9409-4775-a696-3ede4c598e2e.png">

**Comment by theref** [comment]
- [ ] We don't use weights, but the indexing is still important
<img width="771" alt="Screenshot 2023-01-16 at 10 59 19" src="https://user-images.githubusercontent.com/4128101/212650641-e2908faf-4d7d-440b-8869-a4727b2672a1.png">

**Comment by theref** [comment]
- [ ] Are we going to be aggregating decryption shares?
<img width="804" alt="Screenshot 2023-01-16 at 11 08 48" src="https://user-images.githubusercontent.com/4128101/212652624-2e2d10ee-fa54-4030-8e9a-6652f4d4bf35.png">

**Comment by cygnusv** [comment]
> * [ ]  Are we going to be aggregating decryption shares?
> 
> <img alt="Screenshot 2023-01-16 at 11 08 48" width="804" src="https://user-images.githubusercontent.com/4128101/212652624-2e2d10ee-fa54-4030-8e9a-6652f4d4bf35.png">

No, my understanding is that this makes sense for Ferveo original implementation, where a node (with a single private blinding key `ek_i`) may have many private shares, and the corresponding decryption shares can be aggregated.

**Comment by theref** [comment]
yeah, i couldn't think of any scenario where it would make sense for our use case

**Comment by piotr-roslaniec** [comment]
I found some other checks that I would like to document and verify.

`tpke`:
- [ ] [`verify_blinding`](https://github.com/piotr-roslaniec/ferveo/blob/main/tpke/src/key_share.rs#L22-L22)
- [ ] [`batch_verify_decryption_shares`](https://github.com/piotr-roslaniec/ferveo/blob/main/tpke/src/context.rs#L59-L59)

`ferveo`:
- [ ] [`verify_optimistic`](https://github.com/piotr-roslaniec/ferveo/blob/main/ferveo/src/vss/pvss.rs#L106-L106)
- [ ] [ `verify_full`](https://github.com/piotr-roslaniec/ferveo/blob/main/ferveo/src/vss/pvss.rs#L118-L118)

**Comment by piotr-roslaniec** [comment]
Yes, these are from the original Ferveo source code, and I'd like to figure out what they do, how to use them, whether we need them etc.

**Comment by piotr-roslaniec** [comment]
> We don't use weights, but the indexing is still important
Marking as complete since `ferveo` validators have a `share_index` attributed to them.

**Comment by piotr-roslaniec** [comment]
Not sure how to compute 4.4.4 for a simple tDec variant. In this variant, $D_i$ is of type `Fqk` (product of pairing), but we need to be `G1Prepared` for $e(D_i, B_i)$ to work.

**Comment by piotr-roslaniec** [comment]
`verify_blinding` doesn't work i.e. the original code seems to be implemented incorrectly. I can't find a reference to this operation in the docs or in the whitepaper.

@cygnusv, is this something we would like to explore further, or should we drop `verify_blinding`?

**Comment by piotr-roslaniec** [comment]
If [`blinding_key`](https://github.com/piotr-roslaniec/ferveo/blob/main/tpke/src/key_share.rs#L15), $B_i = [b] dk_i$, is the same as [`PublicKey::encryption_key`](https://github.com/piotr-roslaniec/ferveo/blob/main/ferveo-common/src/keypair.rs#L34-L34) of DKG validator, then `verify_blinding` in `tpke` is effectively the same check that `verify_full` in `ferveo` does:
- $e(G_1, \hat{Y}{i,\omega_j}) = e(A_{i,\omega_j}, ek_i)$ `verify_full`
-  $e(g, Y_i) = e(A_i, [b] H)$, `verify_blinding`

If $B_i = [b] dk_i = b [H]$ doesn't hold, then I don't know what 'verify_blidining is supposed to check`.

**Comment by piotr-roslaniec** [comment]
> Not sure how to compute 4.4.4 for a simple tDec variant. In this variant, Di is of type `Fqk` (product of pairing), but we need to be `G1Prepared` for e(Di,Bi) to work.

Naive rewrite doesn't make sense here anyway, since in simple tDec decryption share is defined as $C_i=e(U,Z_i)$, and in fast tDec as $D_i=[b−1]U$.

So instead of  $e(D_i, B_i) = e(U, -H)$, we should try something like  $C_i = e(U,Z_i) = e(U, -H)$?

**Comment by piotr-roslaniec** [comment]
Closing this as the work will be continued in separate issues mentioned in OP.
