### ISSUE TITLE
Use ciphertext validity checks

### ISSUE THREAD

**Issue by cygnusv** [nucypher/ferveo#4]
Ciphertext validation functions are defined, but for some reason, they're not used. Call them before decryption.

**Comment by theref** [comment]
function is defined at https://github.com/nucypher/ferveo/blob/1022ab2c7ccc689abcc05e5a08df6fb0c2a3fc65/tpke/src/ciphertext.rs#L67

**Comment by piotr-roslaniec** [comment]
Closed by https://github.com/nucypher/ferveo/pull/8
