### ISSUE TITLE
Replace deprecater rust-crypto crate with sha2

### ISSUE THREAD

**Issue by ppoliani** [nucypher/ferveo#83]
The `rust-crypto` create used in `tpke` is deprecated. We should probably use [sha2](https://docs.rs/sha2/latest/sha2/) instead.

**Comment by ppoliani** [comment]
Closing this because I switched to the `ferveo-light-tdec` which seems to have added this change. @piotr-roslaniec I believe it would be helpful if the canonical development branch is called `develop` to be in-line if the naming convention. It will also be simple to know which branch has got the latest dev code.

**Comment by piotr-roslaniec** [comment]
Hi @ppoliani. This project is still in the pre-alpha stage and doesn't have a dev release. I will keep your suggestion in mind, and after merging outstanding PRs we may adapt `dev` branch for the developer release.
