### ISSUE TITLE
Figure out order of magnitude for the number keys in a DKG ritual

### ISSUE THREAD

**Issue by cygnusv** [nucypher/ferveo#9]
where number of keys doesn't necessarily equate to number of nodes

Related issues: https://github.com/nucypher/tdec/issues/85, https://github.com/nucypher/tdec/issues/76

**Comment by piotr-roslaniec** [comment]
Benchmarking the size of the primitives
----------------------------------------------------
- Benchmark [results](https://github.com/nucypher/ferveo/blob/dbe30739ba055f0f62d77bc6df959e4f99f0217a/tpke/BENCHMARK.md)
  - For n=8, the public key share size is 384 bytes, and the private key share is 768 bytes
  - For n=16, the public key share size is 768 bytes, and the private key share is 1536 bytes
- Using `1...n` for threshold, where n is the number of shares, is feasible as confirmed by this [test](https://github.com/nucypher/ferveo/blob/dbe30739ba055f0f62d77bc6df959e4f99f0217a/tpke/src/lib.rs#L257)

**Comment by piotr-roslaniec** [comment]
Superseded by https://github.com/nucypher/tdec/issues/113
